[tool.poetry]
name = "regression"
version = "0.0.0"
description = ""
authors = ["Paweł Kowalski <makr3la@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
flask = "*"
pandas = "*"
scikit-learn = "*"
xlrd = "^1.1"
